# Generated by Django 4.2.13 on 2024-10-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transmitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmitterSerialNumber', models.CharField(max_length=20)),
                ('nodeType', models.CharField(max_length=20)),
                ('nodeSerialNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('allCount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStampUTC', models.DateTimeField(auto_now_add=True)),
                ('lastTimeStamp', models.DateTimeField(null=True)),
                ('deviceUID', models.CharField(max_length=20)),
                ('manufacturerName', models.CharField(max_length=100)),
                ('distance1', models.IntegerField(blank=True, null=True)),
                ('distance2', models.IntegerField(blank=True, null=True)),
                ('distance3', models.IntegerField(blank=True, null=True)),
                ('distance4', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('transmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='ice.transmitter')),
            ],
        ),
    ]
