# Generated by Django 4.2.8 on 2024-05-31 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchorID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transmitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmitterSerialNumber', models.CharField(max_length=20)),
                ('nodeType', models.CharField(max_length=20)),
                ('allCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TagDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(max_length=20)),
                ('TimeStampUTC', models.DateTimeField(auto_now_add=True)),
                ('distance', models.IntegerField()),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_distances', to='ice.anchor')),
            ],
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStampUTC', models.CharField(max_length=20)),
                ('deviceUID', models.CharField(max_length=20)),
                ('manufacturerName', models.CharField(max_length=100)),
                ('distance', models.IntegerField()),
                ('count', models.IntegerField()),
                ('transmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='ice.transmitter')),
            ],
        ),
    ]
