# Generated by Django 4.2.13 on 2024-10-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='status',
            field=models.CharField(default='Out', max_length=10),
        ),
    ]
