# Generated by Django 4.2.16 on 2024-10-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="read",
            name="lastTimeStamp",
            field=models.DateTimeField(null=True),
        ),
    ]
