# Generated by Django 4.2.8 on 2024-05-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='read',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
