# Generated by Django 4.2.8 on 2024-05-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor',
            name='anchorID',
            field=models.CharField(max_length=50),
        ),
    ]
