# Generated by Django 4.2.8 on 2024-06-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='timestamp',
            field=models.CharField(max_length=20),
        ),
    ]
