# Generated by Django 4.2.8 on 2024-06-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0002_alter_read_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
