# Generated by Django 4.2.8 on 2024-06-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0002_alter_read_count_alter_read_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagdistance',
            name='anchor',
        ),
        migrations.AlterField(
            model_name='transmitter',
            name='allCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Anchor',
        ),
        migrations.DeleteModel(
            name='TagDistance',
        ),
    ]
