# Generated by Django 4.2.8 on 2024-06-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0003_alter_read_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='read',
            old_name='timestamp',
            new_name='timestampUTC',
        ),
    ]
