# Generated by Django 4.2.8 on 2024-06-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0004_rename_timestamp_read_timestamputc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='read',
            old_name='timestampUTC',
            new_name='timeStampUTC',
        ),
    ]
