# Generated by Django 4.2.8 on 2024-06-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0005_rename_timestamputc_read_timestamputc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='read',
            old_name='distance',
            new_name='distance1',
        ),
        migrations.AddField(
            model_name='read',
            name='distance2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='read',
            name='distance3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='read',
            name='distance4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
