# Generated by Django 4.2.8 on 2024-06-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0006_rename_distance_read_distance1_read_distance2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmitter',
            name='nodeSerialNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
